<script setup lang="ts">
import { computed, ref } from "vue";
import type { TimelineEvent } from "@/types/session";
const props=defineProps<{events:TimelineEvent[]}>();
const emit=defineEmits<{select:[nodeId:string]}>();
const mode=ref<"risk"|"all">("risk");
const visible=computed(()=>mode.value==="all"?props.events:props.events.filter(item=>item.risk==="high"||item.risk==="critical"));
</script>
<template><section class="timeline"><header><div><small>Event timeline</small><strong>{{visible.length}} relevant events</strong></div><div class="toggle"><button :class="{active:mode==='risk'}" @click="mode='risk'">Risk Only</button><button :class="{active:mode==='all'}" @click="mode='all'">All</button></div></header><div v-if="visible.length" class="event-list"><button v-for="event in visible" :key="event.id" :class="`risk-${event.risk}`" @click="event.nodeId&&emit('select',event.nodeId)"><time>{{event.time}}</time><i/><span><strong>{{event.title}}</strong><small>{{event.detail}}</small></span><b>{{event.risk}}</b></button></div><div v-else class="empty">No events match this filter.</div></section></template>
<style scoped>.timeline{height:100%;padding:14px;border:1px solid var(--trace-border);border-radius:14px;background:#fff;overflow:auto}.timeline header{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.timeline header small,.timeline header strong{display:block}.timeline header small{color:#909aa7;font-size:7px;text-transform:uppercase}.timeline header strong{margin-top:3px;font-size:11px}.toggle{padding:2px;border-radius:8px;background:#eff1f3}.toggle button{padding:5px 8px;border:0;border-radius:6px;color:#7f8997;background:transparent;font-size:8px;cursor:pointer}.toggle button.active{color:var(--trace-ink);background:#fff;box-shadow:0 2px 6px rgba(30,41,59,.08)}.event-list{position:relative}.event-list:before{position:absolute;left:76px;top:10px;bottom:10px;width:1px;background:#e5e8ec;content:""}.event-list button{position:relative;display:grid;grid-template-columns:60px 12px minmax(0,1fr) 54px;align-items:center;gap:10px;width:100%;padding:8px 4px;border:0;border-bottom:1px solid #f0f2f3;text-align:left;background:transparent;cursor:pointer}.event-list time{color:#8994a2;font:8px var(--trace-font-mono)}.event-list i{z-index:1;width:8px;height:8px;border:2px solid #fff;border-radius:50%;background:#96a1ae;box-shadow:0 0 0 1px #cfd5dc}.event-list span strong,.event-list span small{display:block}.event-list span strong{font-size:9px}.event-list span small{margin-top:3px;color:#788493;font-size:8px}.event-list b{justify-self:end;color:#7f8997;font-size:7px;text-transform:uppercase}.event-list .risk-critical i,.event-list .risk-high i{background:var(--trace-red);box-shadow:0 0 0 1px #df8693}.event-list .risk-critical b,.event-list .risk-high b{color:var(--trace-red)}.empty{display:grid;place-items:center;height:70%;color:#8b96a3;font-size:10px}</style>
