<script setup lang="ts">
import { nextTick, ref, watch } from "vue";
import { ChevronDown, ChevronUp, Download } from "lucide-vue-next";
import type { EvidenceStep } from "@/types/evidence";
const props=defineProps<{rows:EvidenceStep[];highlightedStepId?:string}>();
defineEmits<{select:[nodeId:string]}>();
const collapsed=ref(false);
const rowsRoot=ref<HTMLElement>();
watch(()=>props.highlightedStepId,async(id)=>{if(!id)return;await nextTick();rowsRoot.value?.querySelector(`[data-step="${id}"]`)?.scrollIntoView({block:"nearest",behavior:"smooth"});});
</script>
<template><section class="evidence-table" :class="{collapsed}"><header><div><small>Evidence path</small><strong>{{rows.length}} verified steps</strong></div><div><button><Download :size="14" /> Export</button><button class="icon" @click="collapsed=!collapsed"><ChevronUp v-if="!collapsed" :size="15"/><ChevronDown v-else :size="15"/></button></div></header><div v-if="!collapsed" ref="rowsRoot" class="rows"><div class="table-head"><span>Step</span><span>Evidence</span><span>Detail</span><span>Status</span></div><button v-for="row in rows" :key="row.step" class="table-row" :class="[row.status,{highlighted:row.id===highlightedStepId}]" :data-step="row.id" @click="$emit('select',row.nodeId)"><span>{{row.step}}</span><strong>{{row.title}}<small>{{row.type}}</small></strong><code>{{row.detail}}</code><b>{{row.status}}</b></button><div v-if="!rows.length" class="empty">No evidence steps available.</div></div></section></template>
<style scoped>
.evidence-table{height:100%;overflow:hidden;border:1px solid var(--trace-border);border-radius:13px;background:#fff;box-shadow:0 6px 18px rgba(30,41,59,.04);transition:height 220ms cubic-bezier(.2,.8,.2,1)}.evidence-table.collapsed{height:52px}header{display:flex;align-items:center;justify-content:space-between;height:50px;padding:0 13px;border-bottom:1px solid #e9ecef}header small,header strong{display:block}header small{color:#8a94a2;font-size:8px;letter-spacing:.13em;text-transform:uppercase}header strong{margin-top:2px;font-size:11px}header>div:last-child{display:flex;gap:6px}header button{display:flex;align-items:center;gap:5px;padding:6px 9px;border:1px solid #e0e4e9;border-radius:8px;color:#687486;background:#fff;font-size:9px;cursor:pointer;transition:color 160ms ease,border-color 160ms ease,transform 180ms cubic-bezier(.2,.8,.2,1)}header button:hover{color:var(--trace-red);border-color:#e8bec5;transform:translateY(-1px)}header button.icon{display:grid;width:29px;padding:0;place-items:center}.rows{height:calc(100% - 50px);overflow:auto;scroll-behavior:smooth}.table-head,.table-row{display:grid;grid-template-columns:52px minmax(180px,1.2fr) minmax(180px,1fr) 80px;align-items:center;gap:10px;padding:0 12px}.table-head{height:26px;color:#98a1ad;background:#f4f5f6;font-size:8px;text-transform:uppercase;letter-spacing:.08em}.table-row{width:100%;min-height:35px;border:0;border-top:1px solid #f0f2f4;text-align:left;background:#fff;font-size:9px;cursor:pointer;transition:background-color 170ms ease,box-shadow 170ms ease}.table-row:hover{background:#fafafa}.table-row>span{font-family:var(--trace-font-mono);color:#8993a1}.table-row strong{font-size:9px}.table-row strong small{display:inline;margin-left:7px;color:#98a1ad;font-weight:500}.table-row code{overflow:hidden;color:#687486;text-overflow:ellipsis;white-space:nowrap;font-size:8px}.table-row b{justify-self:start;padding:3px 6px;border-radius:6px;color:#657184;background:#eef1f3;font-size:8px;text-transform:uppercase}.table-row.critical,.table-row.blocked{background:#fffafa}.table-row.critical b,.table-row.blocked b{color:var(--trace-red);background:#fff0f0}.table-row.highlighted{position:relative;background:#fff3f3;box-shadow:inset 3px 0 var(--trace-red);animation:highlight-in .35s ease}.empty{padding:18px;color:#8993a1;text-align:center;font-size:9px}@keyframes highlight-in{from{background:#ffdeda}}
</style>
