<script setup lang="ts">
import {computed,ref} from "vue";
import {useRouter} from "vue-router";
import {NMessageProvider} from "naive-ui";
import {Filter,Search} from "lucide-vue-next";
import ProductPageLayout from "@/layouts/ProductPageLayout.vue";
import {useRuntimeStore} from "@/stores/runtimeStore";
import type {Decision,RiskLevel} from "@/types/session";

const store=useRuntimeStore();const router=useRouter();
const decision=ref<Decision|"all">("all");const risk=ref<RiskLevel|"all">("all");const kind=ref<string>("all");const query=ref("");
const decisionLabels:Record<Decision,string>={block:"拦截",review:"待审核",allow:"允许"};
const riskLabels:Record<RiskLevel,string>={critical:"严重",high:"高风险",medium:"中风险",low:"低风险"};
const kindLabels:Record<string,string>={shell:"Shell 命令",filesystem:"文件系统",transform:"数据转换",network:"网络请求"};
const visible=computed(()=>store.toolCalls.filter(call=>(decision.value==="all"||call.decision===decision.value)&&(risk.value==="all"||call.riskLevel===risk.value)&&(kind.value==="all"||call.toolKind===kind.value)&&(call.toolName+call.resource+call.sessionId).toLowerCase().includes(query.value.toLowerCase())));
const openCall=(id:string)=>router.push({path:"/runtime",query:{tool_call:id}});
</script>
<template><NMessageProvider><ProductPageLayout eyebrow="审计清单" title="工具调用" description="查看所有会话与运行中的工具执行前决策。"><template #actions><div class="result-count"><Filter :size="14"/> {{visible.length}} / {{store.toolCalls.length}} 次调用</div></template><section class="filter-card"><label class="search"><Search :size="15"/><input v-model="query" placeholder="搜索工具、会话或资源"/></label><label>决策<select v-model="decision"><option value="all">全部</option><option value="block">拦截</option><option value="review">待审核</option><option value="allow">允许</option></select></label><label>风险<select v-model="risk"><option value="all">全部</option><option value="critical">严重</option><option value="high">高风险</option><option value="medium">中风险</option><option value="low">低风险</option></select></label><label>类型<select v-model="kind"><option value="all">全部</option><option value="shell">Shell 命令</option><option value="filesystem">文件系统</option><option value="transform">数据转换</option><option value="network">网络请求</option></select></label></section><section class="table-card"><div class="table-head"><span>时间</span><span>会话 / 运行</span><span>工具名称</span><span>类型</span><span>资源</span><span>决策</span><span>风险</span><span>延迟</span><span>策略命中</span></div><button v-for="call in visible" :key="call.id" class="table-row" @click="openCall(call.id)"><code>{{call.time}}</code><span><strong>{{call.sessionId}}</strong><small>{{call.runId}}</small></span><strong>{{call.toolName}}</strong><span>{{kindLabels[call.toolKind]??call.toolKind}}</span><code class="resource">{{call.resource}}</code><b :class="`decision-${call.decision}`">{{decisionLabels[call.decision]}}</b><b :class="`risk-${call.riskLevel}`">{{riskLabels[call.riskLevel]}}</b><code>{{call.latencyMs}} ms</code><span>{{call.policyHits.length||'—'}}</span></button><div v-if="!visible.length" class="empty"><strong>没有匹配的工具调用</strong><span>请调整筛选条件后重试。</span></div></section></ProductPageLayout></NMessageProvider></template>
<style scoped>.result-count{display:flex;align-items:center;gap:7px;padding:8px 11px;border:1px solid var(--trace-border);border-radius:10px;color:#657184;background:#fff;font-size:10px}.filter-card{display:grid;grid-template-columns:minmax(240px,1fr) 150px 150px 150px;gap:10px;margin-bottom:12px;padding:11px;border:1px solid var(--trace-border);border-radius:13px;background:#fff;box-shadow:0 6px 18px rgba(30,41,59,.04)}.filter-card label{display:flex;align-items:center;gap:8px;color:#8993a1;font-size:9px}.filter-card select,.filter-card input{width:100%;border:0;outline:0;color:var(--trace-ink);background:transparent;font-size:10px}.filter-card select{padding:7px;border:1px solid #e2e6ea;border-radius:8px;background:#fafafa}.search{padding:0 10px;border:1px solid #e2e6ea;border-radius:9px}.table-card{min-width:1050px;overflow:hidden;border:1px solid var(--trace-border);border-radius:14px;background:#fff;box-shadow:var(--trace-shadow)}.table-head,.table-row{display:grid;grid-template-columns:90px 1.2fr .8fr .7fr 1.15fr .65fr .65fr .55fr .55fr;align-items:center;gap:10px;padding:0 14px}.table-head{height:35px;color:#8b95a2;background:#f4f5f6;font-size:8px;font-weight:700;text-transform:uppercase;letter-spacing:.06em}.table-row{width:100%;min-height:52px;border:0;border-top:1px solid #edf0f2;text-align:left;background:#fff;cursor:pointer;transition:background-color 150ms ease,box-shadow 150ms ease}.table-row:hover{z-index:1;background:#fff8f7;box-shadow:inset 3px 0 var(--trace-red)}.table-row code,.table-row span{min-width:0;overflow:hidden;color:#6e7a8a;text-overflow:ellipsis;white-space:nowrap;font-size:8px}.table-row strong{font-size:9px}.table-row span strong,.table-row span small{display:block}.table-row span small{margin-top:3px;color:#9aa3af;font-size:7px}.table-row b{justify-self:start;padding:4px 6px;border-radius:6px;color:#657184;background:#eef1f3;font-size:7px;text-transform:uppercase}.table-row .decision-block,.table-row .risk-critical,.table-row .risk-high{color:var(--trace-red);background:#fff0f0}.table-row .decision-allow,.table-row .risk-low{color:#15775c;background:#eaf8f3}.table-row .decision-review,.table-row .risk-medium{color:#a36600;background:#fff6e7}.empty{display:grid;place-items:center;padding:70px;color:#8b96a3}.empty strong{font-size:12px}.empty span{margin-top:5px;font-size:9px}</style>
